### ISSUE TITLE
onChange event listener prevents automated completion

### ISSUE THREAD

**Issue by EthosProjects** [heliacer/aigaite#3]
It's in my opinion strange for this to be an intended feature, but multiple different challenges require that you type the answer with a keyboard. The hide, gates, binary, and algorithm objectives all make use of an `onChange` which isn't fired when changing the value with `.value = ...`

I imagine this is not the intended behavior, since needing to interact with the DOM directly with human peripherals is not very AI-esque.

**Comment by heliacer** [comment]
@EthosProjects Thanks for the feedback!
That's a good point - I hadn’t thought that far initially, but I’m definitely considering adding this 🙂
I might expand this even further since I really like how it turned out - If you wish to contribute, feel free!

**Comment by EthosProjects** [comment]
Ordinarily, I would submit a pull request, but I actually don't know react or typescript. I only vaguely understand how the code works. After an embarassingly long time, I found a solution that could tell react to do the event, but I think this is unsatisfactory because it requires going through the source code to find out that the code is written in react rather than solving the puzzles using only the dev console. Essentially, if this was closed source and obfuscated, I never could've solved it. 

```js
const reactJSChangeInput = (input, newValue) => {
	const nativeInputValueSetter = Object.getOwnPropertyDescriptor(window.HTMLInputElement.prototype, 'value').set;
	nativeInputValueSetter.call(input, newValue);
	const event = new Event('input', { bubbles: true });
	input.dispatchEvent(event);
};
```

Other notes are that the case of the proceed buttons is not fully consistent. One of them is "Proceed" and the rest are "proceed" which disrupts smooth automation. It's also not totally clear how you unlock master mode. I learned from combing through the source code. I was lucky enough to locate the commit where you added master mode which made it quicker. Otherwise, I would've had to comb through dozens of files to find the condition. I'll submit pull a pull request for these issues shortly, as I do know how they work. 

https://gist.github.com/EthosProjects/f8d5ca5f3714eb6a00e579fbae51cc30

This is my solution to your game. Admittedly, the Map on line 48 is AI generated. I wrote the first entry `new Map([['1-4-9-16-25', '36']]).get([...document.querySelectorAll("p")].slice(1).map(p => p.textContent).join("-")))`, fed chatGPT the following: 

```typescript
private algorithms: alogrithmType[] = [
    { sequence: [0, 1, 1, 2, 3, 5], result: 8 }, // Fibonacci
    { sequence: [2, 4, 8, 16, 32], result: 64 }, // Powers of 2
    { sequence: [1, 4, 9, 16, 25], result: 36 }, // Squares
    { sequence: [3, 6, 9, 12, 15], result: 18 },
  ]
```

This was because in order to automate that objective, finding each algorithm and hardcoding it would require me to brute force  it until I hopefully got each sequence, or feeding it to an actual AI which would've been silly.

**Comment by heliacer** [comment]
Wow! 🤯  I'm genuinely blown away by the effort you put into this - despite not being entirely familiar with the stack - that's some real dedication 💪 

The script you shared is absolutely bonkers (in a good way)! Automating the game in 0.124 seconds and figuring out how to trigger React events with that `reactJSChangeInput` function is super impressive - I'll find out a way to link it in the repository

Thanks again for all your input 😊
